/*
|--------------------------------------------|
         ⚡️ Generated by Agentsmith ⚡️
      ⚠️ Do not edit this file directly ⚠️
|--------------------------------------------|
*/
export type PromptVariables__hey__0_0_1 = never;
export type PromptConfig__hey__0_0_1 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__hey__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__hey__0_0_1;
  variables: PromptVariables__hey__0_0_1;
  content: string;
};
export type Prompt__hey = {
  name: 'hey';
  slug: 'hey';
  versions: {
    latest: never;
    '0.0.1': PromptVersion__hey__0_0_1;
  };
};
export type Globals = {};
export type Agency = {
  prompts: {
    hey: Prompt__hey;
  };
  globals: Globals;
};
